### PR TITLE
Add option to display first and/or last page number to pager

### PR DESCRIPTION
**Pull request by leebarbara**
New options: DisplayFirstPageNumber and DisplayLastPageNumber
Default value: false

### CODE REVIEW

**Comment by leebarbara** [comment]
You can see the changes here: https://github.com/martijnboland/MvcPaging/pull/77/commits/1c663c71e3b191c7cd38287dbdb676d920f612b4

**Comment by martijnboland** [comment]
Merged, thank you very much! 
In the demo, I changed the 'Paging with filtering #2' example to use the new options. 

A new release will come shortly.

**Comment by leebarbara** [comment]
Great thank you!

**Comment by martijnboland** [comment]
released: https://www.nuget.org/packages/MvcPaging/

**Pull request merged**
